version: "3.8"
services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.10
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
